name: Markdown Lint

on:
  push:
    branches: [main]

jobs:
  markdown-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          globs: "**/*.md"
          config: |
            {
              "MD025": false,
              "MD036": false
            }
